db:
  image: mysql:latest
  ports:
    - "42333:3306"
  environment:
    MYSQL_DATABASE: example_db
    MYSQL_USER: example_db_user
    MYSQL_PASSWORD: example_db_pass
  volumes:
    - "./db:/docker-entrypoint-initdb.d"