# MySQL database shared with tomcat containers.
db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: mkyong
    MYSQL_USER: root
    MYSQL_PASSWORD: password
  volumes:
    - "./db:/docker-entrypoint-initdb.d"
