# MySQL database shared with tomcat containers.
db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: nimda
    MYSQL_DATABASE: mkyong
    MYSQL_USER: mkyong_db_user
    MYSQL_PASSWORD: mkyong_db_pass
  volumes:
    - "./db:/docker-entrypoint-initdb.d"